version: 2
updates:
  - package-ecosystem: 'gomod' # See documentation for possible values
    directory: / # Location of package manifests
    schedule:
      interval: 'weekly'
    # Group updates base on dependency name pattern
    groups:
      go:
        patterns:
          - 'github.com*'
          - 'golang.org*'
          - 'gopkg.in*'
          - 'go.mongodb.org*'
    assignees:
      - 'algo7'

  - package-ecosystem: 'github-actions'
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'algo7'
